#!/bin/bash
echo "bringing up wifi interface"
sudo ifconfig wlan0 up
sudo ifconfig wlan0 192.168.1.1 netmask 255.255.255.0

echo "starting AP"
sudo hostapd -dd hostapd/hostapd.conf &

sudo dnsmasq -C dnsmasq/dnsmasq.conf -p 54
sudo maradns -f maradns/mararc &


